### ISSUE TITLE
Hangars no longer public access

### ISSUE THREAD

**Issue by cruxxansata** [Eclipse-Station/Eclipse-Station-13#262] opened 2019-11-02 08:02 UTC
#### Brief description of the issue
Tried to exit the hangar after arriving on the station, found I did not have access to the hangar doors.

#### What you expected to happen
For the hangars to be publicly-accessible.

#### What actually happened
The shuttles are now inaccessible to station crew and the station is inaccessible to people from the surface. That is, except for pilots and likely explorers and anyone with teleporter access.

#### Steps to reproduce
Go to hangar
Fail
Cry

#### Additional info:
Server revision: 7d9892ccee2166237ea8af9c - 2019-11-02
![dreamseeker_2019-11-02_02-57-46](https://user-images.githubusercontent.com/13389337/68067971-19c91c00-fd1d-11e9-83f7-eb6abd2bf873.png)

Also, you can access the shuttle control rooms but *not* the hangars. Worth noting.

**Comment by EvilJackCarver** [comment] 2019-11-02 16:21
Regression of hangar issue. Caused by #256. High priority

**Comment by EvilJackCarver** [comment] 2019-11-03 06:31
Should be fixed by #265. Please reopen this if it is not.

**Closed by EvilJackCarver** 2019-11-03 06:31 UTC
Labels: Map changes, Priority: High, bug
