### ISSUE TITLE
Ghosts lose ability to examine players during the round

### ISSUE THREAD

**Issue by Chatter42** [Eclipse-Station/Eclipse-Station-13#244] opened 2019-09-24 06:57 UTC
#### Brief description of the issue
RE: Title
#### What you expected to happen
Ghosts are normally and consistently able to examine anything and everything, including and especially players.
#### What actually happened
At some point after the round begins at no specific times, and possibly from the start of the round, ghosts stop being able to examine characters.
#### Steps to reproduce
1. Be a ghost
2. Observe as normal
3. Eventually, you lose the ability to examine characters.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
f1b221316a36bdfdc5ff2b87
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by EvilJackCarver** [comment] 2019-09-24 19:13
Closing as duplicate of #241

**Closed by EvilJackCarver** 2019-09-24 19:13 UTC
Labels: bug, duplicate
