### ISSUE TITLE
Character previews scandalously nude

### ISSUE THREAD

**Issue by Leon9621** [Eclipse-Station/Eclipse-Station-13#235] opened 2019-09-14 05:25 UTC
#### Brief description of the issue
character previews don't spawn with clothes currently, whether job related or loadout related
#### What you expected to happen
Characters would properly display their clothes
#### What actually happened
characters show up for preview in their birthday suit
#### Steps to reproduce
Look at a character in 
#### Additional info:
 - **Server Revision**: f68b4e3e1b53cc015bb3123e - 2019-08-16

**Comment by EvilJackCarver** [comment] 2019-09-14 06:22
Closing as duplicate of #236 - although this one technically came first, the other has more details.

**Closed by EvilJackCarver** 2019-09-14 06:22 UTC
Labels: bug, duplicate
